/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangTypeOfCourseandScheduleThRouteImport } from './routes/$lang/type-of-courseand-schedule-th'
import { Route as LangTypeOfCourseandScheduleEnRouteImport } from './routes/$lang/type-of-courseand-schedule-en'
import { Route as LangRegisterEmailThRouteImport } from './routes/$lang/register-email-th'
import { Route as LangRegisterEmailEnRouteImport } from './routes/$lang/register-email-en'
import { Route as LangPlacethRouteImport } from './routes/$lang/placeth'
import { Route as LangPlaceenRouteImport } from './routes/$lang/placeen'
import { Route as LangNewsthRouteImport } from './routes/$lang/newsth'
import { Route as LangNewsenRouteImport } from './routes/$lang/newsen'
import { Route as LangMasterthRouteImport } from './routes/$lang/masterth'
import { Route as LangMasterenRouteImport } from './routes/$lang/masteren'
import { Route as LangHomethRouteImport } from './routes/$lang/hometh'
import { Route as LangHomeenRouteImport } from './routes/$lang/homeen'
import { Route as LangHomeSaraburiThRouteImport } from './routes/$lang/home-saraburi-th'
import { Route as LangHomeSaraburiEnRouteImport } from './routes/$lang/home-saraburi-en'
import { Route as LangHomePhuketThRouteImport } from './routes/$lang/home-phuket-th'
import { Route as LangHomePhuketEnRouteImport } from './routes/$lang/home-phuket-en'
import { Route as LangHomeHatyaiThRouteImport } from './routes/$lang/home-hatyai-th'
import { Route as LangHomeHatyaiEnRouteImport } from './routes/$lang/home-hatyai-en'
import { Route as LangHomeBangkokThRouteImport } from './routes/$lang/home-bangkok-th'
import { Route as LangHomeBangkokEnRouteImport } from './routes/$lang/home-bangkok-en'
import { Route as LangExperienceThRouteImport } from './routes/$lang/experience-th'
import { Route as LangExperienceEnRouteImport } from './routes/$lang/experience-en'
import { Route as LangDhammathRouteImport } from './routes/$lang/dhammath'
import { Route as LangDhammaenRouteImport } from './routes/$lang/dhammaen'
import { Route as LangCourseSaraburiThRouteImport } from './routes/$lang/course-saraburi-th'
import { Route as LangCourseSaraburiEnRouteImport } from './routes/$lang/course-saraburi-en'
import { Route as LangCoursePhuketThRouteImport } from './routes/$lang/course-phuket-th'
import { Route as LangCoursePhuketEnRouteImport } from './routes/$lang/course-phuket-en'
import { Route as LangCourseHatyaiThRouteImport } from './routes/$lang/course-hatyai-th'
import { Route as LangCourseHatyaiEnRouteImport } from './routes/$lang/course-hatyai-en'
import { Route as LangCourseBangkokThRouteImport } from './routes/$lang/course-bangkok-th'
import { Route as LangCourseBangkokEnRouteImport } from './routes/$lang/course-bangkok-en'
import { Route as LangAboutUsThRouteImport } from './routes/$lang/about-us-th'
import { Route as LangAboutUsEnRouteImport } from './routes/$lang/about-us-en'
import { Route as LangSlugRouteImport } from './routes/$lang/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTypeOfCourseandScheduleThRoute =
  LangTypeOfCourseandScheduleThRouteImport.update({
    id: '/type-of-courseand-schedule-th',
    path: '/type-of-courseand-schedule-th',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangTypeOfCourseandScheduleEnRoute =
  LangTypeOfCourseandScheduleEnRouteImport.update({
    id: '/type-of-courseand-schedule-en',
    path: '/type-of-courseand-schedule-en',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangRegisterEmailThRoute = LangRegisterEmailThRouteImport.update({
  id: '/register-email-th',
  path: '/register-email-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangRegisterEmailEnRoute = LangRegisterEmailEnRouteImport.update({
  id: '/register-email-en',
  path: '/register-email-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPlacethRoute = LangPlacethRouteImport.update({
  id: '/placeth',
  path: '/placeth',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPlaceenRoute = LangPlaceenRouteImport.update({
  id: '/placeen',
  path: '/placeen',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangNewsthRoute = LangNewsthRouteImport.update({
  id: '/newsth',
  path: '/newsth',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangNewsenRoute = LangNewsenRouteImport.update({
  id: '/newsen',
  path: '/newsen',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangMasterthRoute = LangMasterthRouteImport.update({
  id: '/masterth',
  path: '/masterth',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangMasterenRoute = LangMasterenRouteImport.update({
  id: '/masteren',
  path: '/masteren',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomethRoute = LangHomethRouteImport.update({
  id: '/hometh',
  path: '/hometh',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomeenRoute = LangHomeenRouteImport.update({
  id: '/homeen',
  path: '/homeen',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomeSaraburiThRoute = LangHomeSaraburiThRouteImport.update({
  id: '/home-saraburi-th',
  path: '/home-saraburi-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomeSaraburiEnRoute = LangHomeSaraburiEnRouteImport.update({
  id: '/home-saraburi-en',
  path: '/home-saraburi-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomePhuketThRoute = LangHomePhuketThRouteImport.update({
  id: '/home-phuket-th',
  path: '/home-phuket-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomePhuketEnRoute = LangHomePhuketEnRouteImport.update({
  id: '/home-phuket-en',
  path: '/home-phuket-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomeHatyaiThRoute = LangHomeHatyaiThRouteImport.update({
  id: '/home-hatyai-th',
  path: '/home-hatyai-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomeHatyaiEnRoute = LangHomeHatyaiEnRouteImport.update({
  id: '/home-hatyai-en',
  path: '/home-hatyai-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomeBangkokThRoute = LangHomeBangkokThRouteImport.update({
  id: '/home-bangkok-th',
  path: '/home-bangkok-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHomeBangkokEnRoute = LangHomeBangkokEnRouteImport.update({
  id: '/home-bangkok-en',
  path: '/home-bangkok-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangExperienceThRoute = LangExperienceThRouteImport.update({
  id: '/experience-th',
  path: '/experience-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangExperienceEnRoute = LangExperienceEnRouteImport.update({
  id: '/experience-en',
  path: '/experience-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDhammathRoute = LangDhammathRouteImport.update({
  id: '/dhammath',
  path: '/dhammath',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDhammaenRoute = LangDhammaenRouteImport.update({
  id: '/dhammaen',
  path: '/dhammaen',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCourseSaraburiThRoute = LangCourseSaraburiThRouteImport.update({
  id: '/course-saraburi-th',
  path: '/course-saraburi-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCourseSaraburiEnRoute = LangCourseSaraburiEnRouteImport.update({
  id: '/course-saraburi-en',
  path: '/course-saraburi-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCoursePhuketThRoute = LangCoursePhuketThRouteImport.update({
  id: '/course-phuket-th',
  path: '/course-phuket-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCoursePhuketEnRoute = LangCoursePhuketEnRouteImport.update({
  id: '/course-phuket-en',
  path: '/course-phuket-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCourseHatyaiThRoute = LangCourseHatyaiThRouteImport.update({
  id: '/course-hatyai-th',
  path: '/course-hatyai-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCourseHatyaiEnRoute = LangCourseHatyaiEnRouteImport.update({
  id: '/course-hatyai-en',
  path: '/course-hatyai-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCourseBangkokThRoute = LangCourseBangkokThRouteImport.update({
  id: '/course-bangkok-th',
  path: '/course-bangkok-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCourseBangkokEnRoute = LangCourseBangkokEnRouteImport.update({
  id: '/course-bangkok-en',
  path: '/course-bangkok-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutUsThRoute = LangAboutUsThRouteImport.update({
  id: '/about-us-th',
  path: '/about-us-th',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutUsEnRoute = LangAboutUsEnRouteImport.update({
  id: '/about-us-en',
  path: '/about-us-en',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSlugRoute = LangSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/$slug': typeof LangSlugRoute
  '/$lang/about-us-en': typeof LangAboutUsEnRoute
  '/$lang/about-us-th': typeof LangAboutUsThRoute
  '/$lang/course-bangkok-en': typeof LangCourseBangkokEnRoute
  '/$lang/course-bangkok-th': typeof LangCourseBangkokThRoute
  '/$lang/course-hatyai-en': typeof LangCourseHatyaiEnRoute
  '/$lang/course-hatyai-th': typeof LangCourseHatyaiThRoute
  '/$lang/course-phuket-en': typeof LangCoursePhuketEnRoute
  '/$lang/course-phuket-th': typeof LangCoursePhuketThRoute
  '/$lang/course-saraburi-en': typeof LangCourseSaraburiEnRoute
  '/$lang/course-saraburi-th': typeof LangCourseSaraburiThRoute
  '/$lang/dhammaen': typeof LangDhammaenRoute
  '/$lang/dhammath': typeof LangDhammathRoute
  '/$lang/experience-en': typeof LangExperienceEnRoute
  '/$lang/experience-th': typeof LangExperienceThRoute
  '/$lang/home-bangkok-en': typeof LangHomeBangkokEnRoute
  '/$lang/home-bangkok-th': typeof LangHomeBangkokThRoute
  '/$lang/home-hatyai-en': typeof LangHomeHatyaiEnRoute
  '/$lang/home-hatyai-th': typeof LangHomeHatyaiThRoute
  '/$lang/home-phuket-en': typeof LangHomePhuketEnRoute
  '/$lang/home-phuket-th': typeof LangHomePhuketThRoute
  '/$lang/home-saraburi-en': typeof LangHomeSaraburiEnRoute
  '/$lang/home-saraburi-th': typeof LangHomeSaraburiThRoute
  '/$lang/homeen': typeof LangHomeenRoute
  '/$lang/hometh': typeof LangHomethRoute
  '/$lang/masteren': typeof LangMasterenRoute
  '/$lang/masterth': typeof LangMasterthRoute
  '/$lang/newsen': typeof LangNewsenRoute
  '/$lang/newsth': typeof LangNewsthRoute
  '/$lang/placeen': typeof LangPlaceenRoute
  '/$lang/placeth': typeof LangPlacethRoute
  '/$lang/register-email-en': typeof LangRegisterEmailEnRoute
  '/$lang/register-email-th': typeof LangRegisterEmailThRoute
  '/$lang/type-of-courseand-schedule-en': typeof LangTypeOfCourseandScheduleEnRoute
  '/$lang/type-of-courseand-schedule-th': typeof LangTypeOfCourseandScheduleThRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/$slug': typeof LangSlugRoute
  '/$lang/about-us-en': typeof LangAboutUsEnRoute
  '/$lang/about-us-th': typeof LangAboutUsThRoute
  '/$lang/course-bangkok-en': typeof LangCourseBangkokEnRoute
  '/$lang/course-bangkok-th': typeof LangCourseBangkokThRoute
  '/$lang/course-hatyai-en': typeof LangCourseHatyaiEnRoute
  '/$lang/course-hatyai-th': typeof LangCourseHatyaiThRoute
  '/$lang/course-phuket-en': typeof LangCoursePhuketEnRoute
  '/$lang/course-phuket-th': typeof LangCoursePhuketThRoute
  '/$lang/course-saraburi-en': typeof LangCourseSaraburiEnRoute
  '/$lang/course-saraburi-th': typeof LangCourseSaraburiThRoute
  '/$lang/dhammaen': typeof LangDhammaenRoute
  '/$lang/dhammath': typeof LangDhammathRoute
  '/$lang/experience-en': typeof LangExperienceEnRoute
  '/$lang/experience-th': typeof LangExperienceThRoute
  '/$lang/home-bangkok-en': typeof LangHomeBangkokEnRoute
  '/$lang/home-bangkok-th': typeof LangHomeBangkokThRoute
  '/$lang/home-hatyai-en': typeof LangHomeHatyaiEnRoute
  '/$lang/home-hatyai-th': typeof LangHomeHatyaiThRoute
  '/$lang/home-phuket-en': typeof LangHomePhuketEnRoute
  '/$lang/home-phuket-th': typeof LangHomePhuketThRoute
  '/$lang/home-saraburi-en': typeof LangHomeSaraburiEnRoute
  '/$lang/home-saraburi-th': typeof LangHomeSaraburiThRoute
  '/$lang/homeen': typeof LangHomeenRoute
  '/$lang/hometh': typeof LangHomethRoute
  '/$lang/masteren': typeof LangMasterenRoute
  '/$lang/masterth': typeof LangMasterthRoute
  '/$lang/newsen': typeof LangNewsenRoute
  '/$lang/newsth': typeof LangNewsthRoute
  '/$lang/placeen': typeof LangPlaceenRoute
  '/$lang/placeth': typeof LangPlacethRoute
  '/$lang/register-email-en': typeof LangRegisterEmailEnRoute
  '/$lang/register-email-th': typeof LangRegisterEmailThRoute
  '/$lang/type-of-courseand-schedule-en': typeof LangTypeOfCourseandScheduleEnRoute
  '/$lang/type-of-courseand-schedule-th': typeof LangTypeOfCourseandScheduleThRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/$slug': typeof LangSlugRoute
  '/$lang/about-us-en': typeof LangAboutUsEnRoute
  '/$lang/about-us-th': typeof LangAboutUsThRoute
  '/$lang/course-bangkok-en': typeof LangCourseBangkokEnRoute
  '/$lang/course-bangkok-th': typeof LangCourseBangkokThRoute
  '/$lang/course-hatyai-en': typeof LangCourseHatyaiEnRoute
  '/$lang/course-hatyai-th': typeof LangCourseHatyaiThRoute
  '/$lang/course-phuket-en': typeof LangCoursePhuketEnRoute
  '/$lang/course-phuket-th': typeof LangCoursePhuketThRoute
  '/$lang/course-saraburi-en': typeof LangCourseSaraburiEnRoute
  '/$lang/course-saraburi-th': typeof LangCourseSaraburiThRoute
  '/$lang/dhammaen': typeof LangDhammaenRoute
  '/$lang/dhammath': typeof LangDhammathRoute
  '/$lang/experience-en': typeof LangExperienceEnRoute
  '/$lang/experience-th': typeof LangExperienceThRoute
  '/$lang/home-bangkok-en': typeof LangHomeBangkokEnRoute
  '/$lang/home-bangkok-th': typeof LangHomeBangkokThRoute
  '/$lang/home-hatyai-en': typeof LangHomeHatyaiEnRoute
  '/$lang/home-hatyai-th': typeof LangHomeHatyaiThRoute
  '/$lang/home-phuket-en': typeof LangHomePhuketEnRoute
  '/$lang/home-phuket-th': typeof LangHomePhuketThRoute
  '/$lang/home-saraburi-en': typeof LangHomeSaraburiEnRoute
  '/$lang/home-saraburi-th': typeof LangHomeSaraburiThRoute
  '/$lang/homeen': typeof LangHomeenRoute
  '/$lang/hometh': typeof LangHomethRoute
  '/$lang/masteren': typeof LangMasterenRoute
  '/$lang/masterth': typeof LangMasterthRoute
  '/$lang/newsen': typeof LangNewsenRoute
  '/$lang/newsth': typeof LangNewsthRoute
  '/$lang/placeen': typeof LangPlaceenRoute
  '/$lang/placeth': typeof LangPlacethRoute
  '/$lang/register-email-en': typeof LangRegisterEmailEnRoute
  '/$lang/register-email-th': typeof LangRegisterEmailThRoute
  '/$lang/type-of-courseand-schedule-en': typeof LangTypeOfCourseandScheduleEnRoute
  '/$lang/type-of-courseand-schedule-th': typeof LangTypeOfCourseandScheduleThRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/$slug'
    | '/$lang/about-us-en'
    | '/$lang/about-us-th'
    | '/$lang/course-bangkok-en'
    | '/$lang/course-bangkok-th'
    | '/$lang/course-hatyai-en'
    | '/$lang/course-hatyai-th'
    | '/$lang/course-phuket-en'
    | '/$lang/course-phuket-th'
    | '/$lang/course-saraburi-en'
    | '/$lang/course-saraburi-th'
    | '/$lang/dhammaen'
    | '/$lang/dhammath'
    | '/$lang/experience-en'
    | '/$lang/experience-th'
    | '/$lang/home-bangkok-en'
    | '/$lang/home-bangkok-th'
    | '/$lang/home-hatyai-en'
    | '/$lang/home-hatyai-th'
    | '/$lang/home-phuket-en'
    | '/$lang/home-phuket-th'
    | '/$lang/home-saraburi-en'
    | '/$lang/home-saraburi-th'
    | '/$lang/homeen'
    | '/$lang/hometh'
    | '/$lang/masteren'
    | '/$lang/masterth'
    | '/$lang/newsen'
    | '/$lang/newsth'
    | '/$lang/placeen'
    | '/$lang/placeth'
    | '/$lang/register-email-en'
    | '/$lang/register-email-th'
    | '/$lang/type-of-courseand-schedule-en'
    | '/$lang/type-of-courseand-schedule-th'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/$slug'
    | '/$lang/about-us-en'
    | '/$lang/about-us-th'
    | '/$lang/course-bangkok-en'
    | '/$lang/course-bangkok-th'
    | '/$lang/course-hatyai-en'
    | '/$lang/course-hatyai-th'
    | '/$lang/course-phuket-en'
    | '/$lang/course-phuket-th'
    | '/$lang/course-saraburi-en'
    | '/$lang/course-saraburi-th'
    | '/$lang/dhammaen'
    | '/$lang/dhammath'
    | '/$lang/experience-en'
    | '/$lang/experience-th'
    | '/$lang/home-bangkok-en'
    | '/$lang/home-bangkok-th'
    | '/$lang/home-hatyai-en'
    | '/$lang/home-hatyai-th'
    | '/$lang/home-phuket-en'
    | '/$lang/home-phuket-th'
    | '/$lang/home-saraburi-en'
    | '/$lang/home-saraburi-th'
    | '/$lang/homeen'
    | '/$lang/hometh'
    | '/$lang/masteren'
    | '/$lang/masterth'
    | '/$lang/newsen'
    | '/$lang/newsth'
    | '/$lang/placeen'
    | '/$lang/placeth'
    | '/$lang/register-email-en'
    | '/$lang/register-email-th'
    | '/$lang/type-of-courseand-schedule-en'
    | '/$lang/type-of-courseand-schedule-th'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/$slug'
    | '/$lang/about-us-en'
    | '/$lang/about-us-th'
    | '/$lang/course-bangkok-en'
    | '/$lang/course-bangkok-th'
    | '/$lang/course-hatyai-en'
    | '/$lang/course-hatyai-th'
    | '/$lang/course-phuket-en'
    | '/$lang/course-phuket-th'
    | '/$lang/course-saraburi-en'
    | '/$lang/course-saraburi-th'
    | '/$lang/dhammaen'
    | '/$lang/dhammath'
    | '/$lang/experience-en'
    | '/$lang/experience-th'
    | '/$lang/home-bangkok-en'
    | '/$lang/home-bangkok-th'
    | '/$lang/home-hatyai-en'
    | '/$lang/home-hatyai-th'
    | '/$lang/home-phuket-en'
    | '/$lang/home-phuket-th'
    | '/$lang/home-saraburi-en'
    | '/$lang/home-saraburi-th'
    | '/$lang/homeen'
    | '/$lang/hometh'
    | '/$lang/masteren'
    | '/$lang/masterth'
    | '/$lang/newsen'
    | '/$lang/newsth'
    | '/$lang/placeen'
    | '/$lang/placeth'
    | '/$lang/register-email-en'
    | '/$lang/register-email-th'
    | '/$lang/type-of-courseand-schedule-en'
    | '/$lang/type-of-courseand-schedule-th'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/type-of-courseand-schedule-th': {
      id: '/$lang/type-of-courseand-schedule-th'
      path: '/type-of-courseand-schedule-th'
      fullPath: '/$lang/type-of-courseand-schedule-th'
      preLoaderRoute: typeof LangTypeOfCourseandScheduleThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/type-of-courseand-schedule-en': {
      id: '/$lang/type-of-courseand-schedule-en'
      path: '/type-of-courseand-schedule-en'
      fullPath: '/$lang/type-of-courseand-schedule-en'
      preLoaderRoute: typeof LangTypeOfCourseandScheduleEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/register-email-th': {
      id: '/$lang/register-email-th'
      path: '/register-email-th'
      fullPath: '/$lang/register-email-th'
      preLoaderRoute: typeof LangRegisterEmailThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/register-email-en': {
      id: '/$lang/register-email-en'
      path: '/register-email-en'
      fullPath: '/$lang/register-email-en'
      preLoaderRoute: typeof LangRegisterEmailEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/placeth': {
      id: '/$lang/placeth'
      path: '/placeth'
      fullPath: '/$lang/placeth'
      preLoaderRoute: typeof LangPlacethRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/placeen': {
      id: '/$lang/placeen'
      path: '/placeen'
      fullPath: '/$lang/placeen'
      preLoaderRoute: typeof LangPlaceenRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/newsth': {
      id: '/$lang/newsth'
      path: '/newsth'
      fullPath: '/$lang/newsth'
      preLoaderRoute: typeof LangNewsthRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/newsen': {
      id: '/$lang/newsen'
      path: '/newsen'
      fullPath: '/$lang/newsen'
      preLoaderRoute: typeof LangNewsenRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/masterth': {
      id: '/$lang/masterth'
      path: '/masterth'
      fullPath: '/$lang/masterth'
      preLoaderRoute: typeof LangMasterthRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/masteren': {
      id: '/$lang/masteren'
      path: '/masteren'
      fullPath: '/$lang/masteren'
      preLoaderRoute: typeof LangMasterenRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/hometh': {
      id: '/$lang/hometh'
      path: '/hometh'
      fullPath: '/$lang/hometh'
      preLoaderRoute: typeof LangHomethRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/homeen': {
      id: '/$lang/homeen'
      path: '/homeen'
      fullPath: '/$lang/homeen'
      preLoaderRoute: typeof LangHomeenRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/home-saraburi-th': {
      id: '/$lang/home-saraburi-th'
      path: '/home-saraburi-th'
      fullPath: '/$lang/home-saraburi-th'
      preLoaderRoute: typeof LangHomeSaraburiThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/home-saraburi-en': {
      id: '/$lang/home-saraburi-en'
      path: '/home-saraburi-en'
      fullPath: '/$lang/home-saraburi-en'
      preLoaderRoute: typeof LangHomeSaraburiEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/home-phuket-th': {
      id: '/$lang/home-phuket-th'
      path: '/home-phuket-th'
      fullPath: '/$lang/home-phuket-th'
      preLoaderRoute: typeof LangHomePhuketThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/home-phuket-en': {
      id: '/$lang/home-phuket-en'
      path: '/home-phuket-en'
      fullPath: '/$lang/home-phuket-en'
      preLoaderRoute: typeof LangHomePhuketEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/home-hatyai-th': {
      id: '/$lang/home-hatyai-th'
      path: '/home-hatyai-th'
      fullPath: '/$lang/home-hatyai-th'
      preLoaderRoute: typeof LangHomeHatyaiThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/home-hatyai-en': {
      id: '/$lang/home-hatyai-en'
      path: '/home-hatyai-en'
      fullPath: '/$lang/home-hatyai-en'
      preLoaderRoute: typeof LangHomeHatyaiEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/home-bangkok-th': {
      id: '/$lang/home-bangkok-th'
      path: '/home-bangkok-th'
      fullPath: '/$lang/home-bangkok-th'
      preLoaderRoute: typeof LangHomeBangkokThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/home-bangkok-en': {
      id: '/$lang/home-bangkok-en'
      path: '/home-bangkok-en'
      fullPath: '/$lang/home-bangkok-en'
      preLoaderRoute: typeof LangHomeBangkokEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/experience-th': {
      id: '/$lang/experience-th'
      path: '/experience-th'
      fullPath: '/$lang/experience-th'
      preLoaderRoute: typeof LangExperienceThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/experience-en': {
      id: '/$lang/experience-en'
      path: '/experience-en'
      fullPath: '/$lang/experience-en'
      preLoaderRoute: typeof LangExperienceEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dhammath': {
      id: '/$lang/dhammath'
      path: '/dhammath'
      fullPath: '/$lang/dhammath'
      preLoaderRoute: typeof LangDhammathRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dhammaen': {
      id: '/$lang/dhammaen'
      path: '/dhammaen'
      fullPath: '/$lang/dhammaen'
      preLoaderRoute: typeof LangDhammaenRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/course-saraburi-th': {
      id: '/$lang/course-saraburi-th'
      path: '/course-saraburi-th'
      fullPath: '/$lang/course-saraburi-th'
      preLoaderRoute: typeof LangCourseSaraburiThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/course-saraburi-en': {
      id: '/$lang/course-saraburi-en'
      path: '/course-saraburi-en'
      fullPath: '/$lang/course-saraburi-en'
      preLoaderRoute: typeof LangCourseSaraburiEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/course-phuket-th': {
      id: '/$lang/course-phuket-th'
      path: '/course-phuket-th'
      fullPath: '/$lang/course-phuket-th'
      preLoaderRoute: typeof LangCoursePhuketThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/course-phuket-en': {
      id: '/$lang/course-phuket-en'
      path: '/course-phuket-en'
      fullPath: '/$lang/course-phuket-en'
      preLoaderRoute: typeof LangCoursePhuketEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/course-hatyai-th': {
      id: '/$lang/course-hatyai-th'
      path: '/course-hatyai-th'
      fullPath: '/$lang/course-hatyai-th'
      preLoaderRoute: typeof LangCourseHatyaiThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/course-hatyai-en': {
      id: '/$lang/course-hatyai-en'
      path: '/course-hatyai-en'
      fullPath: '/$lang/course-hatyai-en'
      preLoaderRoute: typeof LangCourseHatyaiEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/course-bangkok-th': {
      id: '/$lang/course-bangkok-th'
      path: '/course-bangkok-th'
      fullPath: '/$lang/course-bangkok-th'
      preLoaderRoute: typeof LangCourseBangkokThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/course-bangkok-en': {
      id: '/$lang/course-bangkok-en'
      path: '/course-bangkok-en'
      fullPath: '/$lang/course-bangkok-en'
      preLoaderRoute: typeof LangCourseBangkokEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about-us-th': {
      id: '/$lang/about-us-th'
      path: '/about-us-th'
      fullPath: '/$lang/about-us-th'
      preLoaderRoute: typeof LangAboutUsThRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about-us-en': {
      id: '/$lang/about-us-en'
      path: '/about-us-en'
      fullPath: '/$lang/about-us-en'
      preLoaderRoute: typeof LangAboutUsEnRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/$slug': {
      id: '/$lang/$slug'
      path: '/$slug'
      fullPath: '/$lang/$slug'
      preLoaderRoute: typeof LangSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangSlugRoute: typeof LangSlugRoute
  LangAboutUsEnRoute: typeof LangAboutUsEnRoute
  LangAboutUsThRoute: typeof LangAboutUsThRoute
  LangCourseBangkokEnRoute: typeof LangCourseBangkokEnRoute
  LangCourseBangkokThRoute: typeof LangCourseBangkokThRoute
  LangCourseHatyaiEnRoute: typeof LangCourseHatyaiEnRoute
  LangCourseHatyaiThRoute: typeof LangCourseHatyaiThRoute
  LangCoursePhuketEnRoute: typeof LangCoursePhuketEnRoute
  LangCoursePhuketThRoute: typeof LangCoursePhuketThRoute
  LangCourseSaraburiEnRoute: typeof LangCourseSaraburiEnRoute
  LangCourseSaraburiThRoute: typeof LangCourseSaraburiThRoute
  LangDhammaenRoute: typeof LangDhammaenRoute
  LangDhammathRoute: typeof LangDhammathRoute
  LangExperienceEnRoute: typeof LangExperienceEnRoute
  LangExperienceThRoute: typeof LangExperienceThRoute
  LangHomeBangkokEnRoute: typeof LangHomeBangkokEnRoute
  LangHomeBangkokThRoute: typeof LangHomeBangkokThRoute
  LangHomeHatyaiEnRoute: typeof LangHomeHatyaiEnRoute
  LangHomeHatyaiThRoute: typeof LangHomeHatyaiThRoute
  LangHomePhuketEnRoute: typeof LangHomePhuketEnRoute
  LangHomePhuketThRoute: typeof LangHomePhuketThRoute
  LangHomeSaraburiEnRoute: typeof LangHomeSaraburiEnRoute
  LangHomeSaraburiThRoute: typeof LangHomeSaraburiThRoute
  LangHomeenRoute: typeof LangHomeenRoute
  LangHomethRoute: typeof LangHomethRoute
  LangMasterenRoute: typeof LangMasterenRoute
  LangMasterthRoute: typeof LangMasterthRoute
  LangNewsenRoute: typeof LangNewsenRoute
  LangNewsthRoute: typeof LangNewsthRoute
  LangPlaceenRoute: typeof LangPlaceenRoute
  LangPlacethRoute: typeof LangPlacethRoute
  LangRegisterEmailEnRoute: typeof LangRegisterEmailEnRoute
  LangRegisterEmailThRoute: typeof LangRegisterEmailThRoute
  LangTypeOfCourseandScheduleEnRoute: typeof LangTypeOfCourseandScheduleEnRoute
  LangTypeOfCourseandScheduleThRoute: typeof LangTypeOfCourseandScheduleThRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangSlugRoute: LangSlugRoute,
  LangAboutUsEnRoute: LangAboutUsEnRoute,
  LangAboutUsThRoute: LangAboutUsThRoute,
  LangCourseBangkokEnRoute: LangCourseBangkokEnRoute,
  LangCourseBangkokThRoute: LangCourseBangkokThRoute,
  LangCourseHatyaiEnRoute: LangCourseHatyaiEnRoute,
  LangCourseHatyaiThRoute: LangCourseHatyaiThRoute,
  LangCoursePhuketEnRoute: LangCoursePhuketEnRoute,
  LangCoursePhuketThRoute: LangCoursePhuketThRoute,
  LangCourseSaraburiEnRoute: LangCourseSaraburiEnRoute,
  LangCourseSaraburiThRoute: LangCourseSaraburiThRoute,
  LangDhammaenRoute: LangDhammaenRoute,
  LangDhammathRoute: LangDhammathRoute,
  LangExperienceEnRoute: LangExperienceEnRoute,
  LangExperienceThRoute: LangExperienceThRoute,
  LangHomeBangkokEnRoute: LangHomeBangkokEnRoute,
  LangHomeBangkokThRoute: LangHomeBangkokThRoute,
  LangHomeHatyaiEnRoute: LangHomeHatyaiEnRoute,
  LangHomeHatyaiThRoute: LangHomeHatyaiThRoute,
  LangHomePhuketEnRoute: LangHomePhuketEnRoute,
  LangHomePhuketThRoute: LangHomePhuketThRoute,
  LangHomeSaraburiEnRoute: LangHomeSaraburiEnRoute,
  LangHomeSaraburiThRoute: LangHomeSaraburiThRoute,
  LangHomeenRoute: LangHomeenRoute,
  LangHomethRoute: LangHomethRoute,
  LangMasterenRoute: LangMasterenRoute,
  LangMasterthRoute: LangMasterthRoute,
  LangNewsenRoute: LangNewsenRoute,
  LangNewsthRoute: LangNewsthRoute,
  LangPlaceenRoute: LangPlaceenRoute,
  LangPlacethRoute: LangPlacethRoute,
  LangRegisterEmailEnRoute: LangRegisterEmailEnRoute,
  LangRegisterEmailThRoute: LangRegisterEmailThRoute,
  LangTypeOfCourseandScheduleEnRoute: LangTypeOfCourseandScheduleEnRoute,
  LangTypeOfCourseandScheduleThRoute: LangTypeOfCourseandScheduleThRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
